sudo: required
services:
  - docker

before_install:
  - docker build -t gary/docker-react -f Dockerfile.dev .

script:
  - docker run gary/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-814232539880"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
